# Servidor
server.port=8081

# Configuración de base de datos (Render inyectará los valores reales)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Driver y Dialecto (Esto ayuda a que no explote por metadatos)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate (ddl-auto en update es seguro para desarrollo/examen)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ajuste para evitar problemas de codificación al arrancar
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
