spring.application.name=ajax
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/sams
spring.datasource.username=root
spring.datasource.password=7Kabz&82S.#w
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true